# Production docker-compose configuration
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://ugc_user:${POSTGRES_PASSWORD}@postgres:5432/ugc_db
      - JWT_SECRET=${JWT_SECRET}
    volumes: []  # No volume mounts in production
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  postgres:
    environment:
      - POSTGRES_DB=ugc_db
      - POSTGRES_USER=ugc_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Remove development tools in production
  redis-commander:
    deploy:
      replicas: 0

  pgadmin:
    deploy:
      replicas: 0